### PR TITLE
Complete gradle port

### PR DESCRIPTION
**Pull request by timyates**
Fix run.sh
Make gradlew runnable on OS X/Linux
Add .gradle to .gitignore
Updated build instructions in README

### CODE REVIEW

**Comment by chriswhocodes** [comment]
Hi Tim, thanks for this PR.

As I recall the gradle build was created by @Ciruman to make DemoFX work on Android and iOS and pulls in all the deps for that (robovm, javafxports, retrolambda etc.)

I don't mind having a single build system and gradle is fine but I think the gradle config needs some refactoring so that desktop users don't pull in all the mobile stuff.

If your gradle-fu is strong (mine isn't) then do you fancy taking a swing at that?

Thanks,

Chris

**Comment by timyates** [comment]
I'll give it a go 😀

**Comment by timyates** [comment]
Any idea if it works on mobile?

Wondering if (for now) it's just cleaner to get it back to a desktop only build? 😄

**Comment by chriswhocodes** [comment]
I'll try and get the mobile stuff working.
Maybe rename the old build.gradle and create a new one for desktop?

**Comment by Ciruman** [comment]
Hi! sorry I read the messages right now.. If there is interest on the mobile port I could help. hat can I do? Update the gradle build, test it on mobile, or remove it :) whatever.

**Comment by timyates** [comment]
Think we'll maybe need two gradle builds, need to investigate how Gluon works so we can target desktop, Android and iOS ;-)

Would be interesting to see the differences in benchmarks across all 3 platforms :-)

Guess this should be another issue?

**Comment by chriswhocodes** [comment]
Hi @timyates @Ciruman I think having 2 gradle builds would be nice:

1 for desktop that doesn't depend on all the RoboVM / JavaFXPorts stuff
1 for mobile that does

Then we can remove the ant build.

I'm currently working on a Raspberry Pi demo script that is based on part 3 but I'll drop the effects that don't work (some of the MediaPlayer stuff I think). Perhaps it would be sensible to have a separate demo script for mobile with lower expectation than the desktop version?

Any help you can give me with the gradle stuff would be appreciated.

Thanks,

Chris

**Comment by Ciruman** [comment]
Hi, 
What's the problem of having one grade with all targets? 
Thanks,
Diego

**Comment by chriswhocodes** [comment]
Hi @Ciruman,

As long as there is a way for non-mobile users to build DemoFX without pulling in all the dependencies for mobile then I'm fine with a single build file.

I think the mobile builds should be named tasks and the default should just build the standalone demo (for desktop / Raspberry Pi etc).

Thanks,

Chris

**Comment by Ciruman** [comment]
Then I will create a gradle just to migrate from ant to gradle and once gradle is working, I will try to add the mobile functionality. Is it ok like this?

I am sorry for all the inconvenience I caused with the port to mobile.

I am not an expert gradle user(I know maven) but I will search how can I do it.

**Comment by Ciruman** [comment]
I create a version in my fork with gradle, I removed all ant and mobile functionalities(not the classes) from the build point of view. 

the scripts run.sh and demofx3.sh are updated and work as expected, softRun.sh not yet(time to sleep).

Next:
Fix softRun.sh
Update readme
Decide what to do with the mobile adaptation(this is something I would like to implement again once gradle build works and the project is clean)

Cheers!

**Comment by chriswhocodes** [comment]
I'll close this PR now and open an issue to add mobile support back to DemoFX.

**Pull request closed without merging**
